### ISSUE TITLE
Some small changes I made but need improvement

### ISSUE THREAD

**Issue by jelenajjo** [vanila-io/pattapp#10]
Regarding this issue #6 I had to duplicate code in two places:
- [#L65-L80](https://github.com/vanila-io/pattapp/blob/master/jelena-index.html#L65-L80)
- [#L84-L96](https://github.com/vanila-io/pattapp/blob/master/jelena-index.html#L84-L96)

I added different `id` like `duplicateText` and `removeText` and in the [script.js](https://github.com/vanila-io/pattapp/blob/master/js/script.js) file I added code [here](https://github.com/vanila-io/pattapp/blob/master/js/script.js#L77-L82).

I don't like that. I think it would be better, more clean, if it would be connected with same class instead of id or something like that. 

Also, it has to be created new code for [opacity range](https://github.com/vanila-io/pattapp/blob/master/js/script.js#L67-L70).

**Comment by shtefcs** [comment]
@jelenajjo can this be closed ?
